### PR TITLE
Feature/str16

### PR DESCRIPTION
**Pull request by daniel-moulton**
Updated Navbar:

- Changed colour schemes, added styling for active and hover pages
- Moved navbar items around
- Other miscellaneous UI changes

### CODE REVIEW

**Comment by Kevvy404** [comment]
Looking good!!

**Review by Kevvy404 — APPROVED** [review]
good progress daniel moulton

**Review by EthanHofton — APPROVED** [review]
Very good work! LGTM

**Comment by daniel-moulton** [comment]
[Base Template Design Impl](https://trello.com/c/ERV84bvL/16-base-template-design-impl)

**Pull request merged**
