### PR TITLE
Feature/str84

### PR DESCRIPTION
**Pull request by Joshua-Weaver1**
Created the hangman minigame.

Features include:

- Randomly selected sustainability themed words
- Responsive hangman image
- Notification if letter already guessed
- Output if user wins or loses

### CODE REVIEW

**Review by daniel-moulton — APPROVED** [review]
lgtm!

**Review by Kevvy404 — APPROVED** [review]
Good job!

**Comment by EthanHofton** [comment]
Does the game have a gameWon variable?

**Comment by Kevvy404** [comment]
[Trivia Game](https://trello.com/c/Ih1eUlKw/55-trivia-game)

**Comment by Joshua-Weaver1** [comment]
[Hangman Page Design](https://trello.com/c/TEBuWoGk/50-hangman-page-design)

**Comment by Joshua-Weaver1** [comment]
[Hangman Page Functionality](https://trello.com/c/XUYSblgF/51-hangman-page-functionality)

**Pull request merged**
